### ISSUE TITLE
Seg Fault when running example

### ISSUE THREAD

**Issue by LetoTheSecond** [laytan/odin-tree-sitter#3]
Hello, I was trying to use these binding to use Tree-sitter to parse USD files using [this parser](https://github.com/ColinKennedy/tree-sitter-usd/) but calling parse_string would seg fault. So I tried to run the example program that is in the repo and it too seg faulted.

I've tried stepping through in gdb to see if I can figure out where the problem is but once it gets inside of tree-sitter itself I get lost trying to follow its parsing loop. Have I missed something simple that I'm overlooking?

<details>
<summary>Debug Output of example/main.odin</summary>
 
 ```
[DEBUG] --- [helpers.odin:165] Parse - new_parse
[DEBUG] --- [helpers.odin:165] Parse - process version:0, version_count:1, state:1, row:0, col:0
[DEBUG] --- [helpers.odin:165] Parse - lex_external state:2, row:0, column:0
[DEBUG] --- [helpers.odin:165] Parse - lex_internal state:85, row:0, column:0
[DEBUG] --- [helpers.odin:165] Lex - consume character:'p'
[DEBUG] --- [helpers.odin:165] Lex - consume character:'a'
[DEBUG] --- [helpers.odin:165] Lex - consume character:'c'
[DEBUG] --- [helpers.odin:165] Lex - consume character:'k'
[DEBUG] --- [helpers.odin:165] Lex - consume character:'a'
[DEBUG] --- [helpers.odin:165] Lex - consume character:'g'
[DEBUG] --- [helpers.odin:165] Lex - consume character:'e'
[DEBUG] --- [helpers.odin:165] Lex - consume character:'p'
[DEBUG] --- [helpers.odin:165] Lex - consume character:'a'
[DEBUG] --- [helpers.odin:165] Lex - consume character:'c'
[DEBUG] --- [helpers.odin:165] Lex - consume character:'k'
[DEBUG] --- [helpers.odin:165] Lex - consume character:'a'
[DEBUG] --- [helpers.odin:165] Lex - consume character:'g'
[DEBUG] --- [helpers.odin:165] Lex - consume character:'e'
[DEBUG] --- [helpers.odin:165] Parse - lexed_lookahead sym:package, size:7
[DEBUG] --- [helpers.odin:165] Parse - shift state:9285
[DEBUG] --- [helpers.odin:165] Parse - process version:0, version_count:1, state:9285, row:0, col:7
[DEBUG] --- [helpers.odin:165] Parse - lex_external state:7, row:0, column:7
[DEBUG] --- [helpers.odin:165] Lex - skip character:' '
[DEBUG] --- [helpers.odin:165] Parse - lex_internal state:0, row:0, column:7
[DEBUG] --- [helpers.odin:165] Lex - skip character:' '
[DEBUG] --- [helpers.odin:165] Lex - consume character:'m'
[DEBUG] --- [helpers.odin:165] Lex - consume character:'a'
[DEBUG] --- [helpers.odin:165] Lex - consume character:'i'
[DEBUG] --- [helpers.odin:165] Lex - consume character:'n'
[DEBUG] --- [helpers.odin:165] Lex - consume character:'m'
[DEBUG] --- [helpers.odin:165] Lex - consume character:'a'
[DEBUG] --- [helpers.odin:165] Parse - lexed_lookahead sym:identifier, size:5
[DEBUG] --- [helpers.odin:165] Parse - shift state:7787
[DEBUG] --- [helpers.odin:165] Parse - process version:0, version_count:1, state:7787, row:0, col:12
[DEBUG] --- [helpers.odin:165] Parse - lex_external state:5, row:0, column:12
[DEBUG] --- [helpers.odin:165] Lex - consume character:10
[DEBUG] --- [helpers.odin:165] Lex - skip character:10
[DEBUG] --- [helpers.odin:165] Lex - consume character:'/'
[DEBUG] --- [helpers.odin:165] Lex - consume character:'/'
[DEBUG] --- [helpers.odin:165] Parse - lexed_lookahead sym:_newline, size:1
[DEBUG] --- [helpers.odin:165] Parse - reduce sym:package_declaration, child_count:2
[DEBUG] --- [helpers.odin:165] Parse - reduce sym:declaration, child_count:1
[DEBUG] --- [helpers.odin:165] Parse - shift state:5913
[DEBUG] --- [helpers.odin:165] Parse - process version:0, version_count:1, state:5913, row:1, col:0
[DEBUG] --- [helpers.odin:165] Parse - lex_external state:2, row:1, column:0
[DEBUG] --- [helpers.odin:165] Lex - skip character:10
[DEBUG] --- [helpers.odin:165] Parse - lex_internal state:85, row:1, column:0
[DEBUG] --- [helpers.odin:165] Lex - skip character:10
[DEBUG] --- [helpers.odin:165] Lex - consume character:'/'
[DEBUG] --- [helpers.odin:165] Lex - consume character:'/'
[DEBUG] --- [helpers.odin:165] Lex - consume character:' '
[DEBUG] --- [helpers.odin:165] Lex - consume character:'G'
[DEBUG] --- [helpers.odin:165] Lex - consume character:'e'
[DEBUG] --- [helpers.odin:165] Lex - consume character:'n'
[DEBUG] --- [helpers.odin:165] Lex - consume character:'e'
[DEBUG] --- [helpers.odin:165] Lex - consume character:'r'
[DEBUG] --- [helpers.odin:165] Lex - consume character:'a'
[DEBUG] --- [helpers.odin:165] Lex - consume character:'t'
[DEBUG] --- [helpers.odin:165] Lex - consume character:'e'
[DEBUG] --- [helpers.odin:165] Lex - consume character:'d'
[DEBUG] --- [helpers.odin:165] Lex - consume character:' '
[DEBUG] --- [helpers.odin:165] Lex - consume character:'t'
[DEBUG] --- [helpers.odin:165] Lex - consume character:'h'
[DEBUG] --- [helpers.odin:165] Lex - consume character:'r'
[DEBUG] --- [helpers.odin:165] Lex - consume character:'o'
[DEBUG] --- [helpers.odin:165] Lex - consume character:'u'
[DEBUG] --- [helpers.odin:165] Lex - consume character:'g'
[DEBUG] --- [helpers.odin:165] Lex - consume character:'h'
[DEBUG] --- [helpers.odin:165] Lex - consume character:' '
[DEBUG] --- [helpers.odin:165] Lex - consume character:'`'
[DEBUG] --- [helpers.odin:165] Lex - consume character:'o'
[DEBUG] --- [helpers.odin:165] Lex - consume character:'d'
[DEBUG] --- [helpers.odin:165] Lex - consume character:'i'
[DEBUG] --- [helpers.odin:165] Lex - consume character:'n'
[DEBUG] --- [helpers.odin:165] Lex - consume character:' '
[DEBUG] --- [helpers.odin:165] Lex - consume character:'r'
[DEBUG] --- [helpers.odin:165] Lex - consume character:'u'
[DEBUG] --- [helpers.odin:165] Lex - consume character:'n'
[DEBUG] --- [helpers.odin:165] Lex - consume character:' '
[DEBUG] --- [helpers.odin:165] Lex - consume character:'b'
[DEBUG] --- [helpers.odin:165] Lex - consume character:'u'
[DEBUG] --- [helpers.odin:165] Lex - consume character:'i'
[DEBUG] --- [helpers.odin:165] Lex - consume character:'l'
[DEBUG] --- [helpers.odin:165] Lex - consume character:'d'
[DEBUG] --- [helpers.odin:165] Lex - consume character:' '
[DEBUG] --- [helpers.odin:165] Lex - consume character:'-'
[DEBUG] --- [helpers.odin:165] Lex - consume character:'-'
[DEBUG] --- [helpers.odin:165] Lex - consume character:' '
[DEBUG] --- [helpers.odin:165] Lex - consume character:'i'
[DEBUG] --- [helpers.odin:165] Lex - consume character:'n'
[DEBUG] --- [helpers.odin:165] Lex - consume character:'s'
[DEBUG] --- [helpers.odin:165] Lex - consume character:'t'
[DEBUG] --- [helpers.odin:165] Lex - consume character:'a'
[DEBUG] --- [helpers.odin:165] Lex - consume character:'l'
[DEBUG] --- [helpers.odin:165] Lex - consume character:'l'
[DEBUG] --- [helpers.odin:165] Lex - consume character:'`'
[DEBUG] --- [helpers.odin:165] Parse - lexed_lookahead sym:comment, size:49
[DEBUG] --- [helpers.odin:165] Parse - shift_extra
[DEBUG] --- [helpers.odin:165] Parse - process version:0, version_count:1, state:5913, row:2, col:48
[DEBUG] --- [helpers.odin:165] Parse - lex_external state:2, row:2, column:48
[DEBUG] --- [helpers.odin:165] Lex - skip character:10
[DEBUG] --- [helpers.odin:165] Parse - lex_internal state:85, row:2, column:48
[DEBUG] --- [helpers.odin:165] Lex - skip character:10
[DEBUG] --- [helpers.odin:165] Lex - consume character:'i'
[DEBUG] --- [helpers.odin:165] Lex - consume character:'m'
[DEBUG] --- [helpers.odin:165] Lex - consume character:'p'
[DEBUG] --- [helpers.odin:165] Lex - consume character:'o'
[DEBUG] --- [helpers.odin:165] Lex - consume character:'r'
[DEBUG] --- [helpers.odin:165] Lex - consume character:'t'
[DEBUG] --- [helpers.odin:165] Lex - consume character:'i'
[DEBUG] --- [helpers.odin:165] Lex - consume character:'m'
[DEBUG] --- [helpers.odin:165] Lex - consume character:'p'
[DEBUG] --- [helpers.odin:165] Lex - consume character:'o'
[DEBUG] --- [helpers.odin:165] Lex - consume character:'r'
[DEBUG] --- [helpers.odin:165] Lex - consume character:'t'
[DEBUG] --- [helpers.odin:165] Parse - lexed_lookahead sym:import, size:7
[DEBUG] --- [helpers.odin:165] Parse - reduce sym:source_file_repeat1, child_count:2
[DEBUG] --- [helpers.odin:165] Parse - shift state:6929
[DEBUG] --- [helpers.odin:165] Parse - process version:0, version_count:1, state:6929, row:3, col:6
[DEBUG] --- [helpers.odin:165] Parse - lex_external state:10, row:3, column:6
[DEBUG] --- [helpers.odin:165] Lex - skip character:' '
[DEBUG] --- [helpers.odin:165] Parse - lex_internal state:0, row:3, column:6
[DEBUG] --- [helpers.odin:165] Lex - skip character:' '
[DEBUG] --- [helpers.odin:165] Lex - consume character:'t'
[DEBUG] --- [helpers.odin:165] Lex - consume character:'s'
[DEBUG] --- [helpers.odin:165] Lex - consume character:'t'
[DEBUG] --- [helpers.odin:165] Parse - lexed_lookahead sym:identifier, size:3
[DEBUG] --- [helpers.odin:165] Parse - shift state:7038
[DEBUG] --- [helpers.odin:165] Parse - process version:0, version_count:1, state:7038, row:3, col:9
[DEBUG] --- [helpers.odin:165] Parse - lex_external state:10, row:3, column:9
[DEBUG] --- [helpers.odin:165] Lex - skip character:' '
[DEBUG] --- [helpers.odin:165] Parse - lex_internal state:0, row:3, column:9
[DEBUG] --- [helpers.odin:165] Lex - skip character:' '
[DEBUG] --- [helpers.odin:165] Lex - consume character:'"'
[DEBUG] --- [helpers.odin:165] Parse - lexed_lookahead sym:", size:2
[DEBUG] --- [helpers.odin:165] Parse - shift state:7443
[DEBUG] --- [helpers.odin:165] Parse - process version:0, version_count:1, state:7443, row:3, col:11
[DEBUG] --- [helpers.odin:165] Parse - lex_external state:11, row:3, column:11
[DEBUG] --- [helpers.odin:165] Parse - lex_internal state:2, row:3, column:11
[DEBUG] --- [helpers.odin:165] Lex - consume character:'.'
[DEBUG] --- [helpers.odin:165] Lex - consume character:'.'
[DEBUG] --- [helpers.odin:165] Lex - consume character:'/'
[DEBUG] --- [helpers.odin:165] Lex - consume character:'t'
[DEBUG] --- [helpers.odin:165] Lex - consume character:'r'
[DEBUG] --- [helpers.odin:165] Lex - consume character:'e'
[DEBUG] --- [helpers.odin:165] Lex - consume character:'e'
[DEBUG] --- [helpers.odin:165] Lex - consume character:'-'
[DEBUG] --- [helpers.odin:165] Lex - consume character:'s'
[DEBUG] --- [helpers.odin:165] Lex - consume character:'i'
[DEBUG] --- [helpers.odin:165] Lex - consume character:'t'
[DEBUG] --- [helpers.odin:165] Lex - consume character:'t'
[DEBUG] --- [helpers.odin:165] Lex - consume character:'e'
[DEBUG] --- [helpers.odin:165] Lex - consume character:'r'
[DEBUG] --- [helpers.odin:165] Parse - lexed_lookahead sym:string_content, size:14
[DEBUG] --- [helpers.odin:165] Parse - shift state:7516
[DEBUG] --- [helpers.odin:165] Parse - process version:0, version_count:1, state:7516, row:3, col:25
[DEBUG] --- [helpers.odin:165] Parse - lex_external state:11, row:3, column:25
[DEBUG] --- [helpers.odin:165] Parse - lex_internal state:2, row:3, column:25
[DEBUG] --- [helpers.odin:165] Lex - consume character:'"'
[DEBUG] --- [helpers.odin:165] Parse - lexed_lookahead sym:", size:1
[DEBUG] --- [helpers.odin:165] Parse - shift state:4161
[DEBUG] --- [helpers.odin:165] Parse - process version:0, version_count:1, state:4161, row:3, col:26
[DEBUG] --- [helpers.odin:165] Parse - lex_external state:5, row:3, column:26
[DEBUG] --- [helpers.odin:165] Lex - consume character:10
[DEBUG] --- [helpers.odin:165] Lex - skip character:10
[DEBUG] --- [helpers.odin:165] Lex - consume character:'/'
[DEBUG] --- [helpers.odin:165] Lex - consume character:'/'
[DEBUG] --- [helpers.odin:165] Parse - lexed_lookahead sym:_newline, size:1
[DEBUG] --- [helpers.odin:165] Parse - reduce sym:_string_literal, child_count:3
[DEBUG] --- [helpers.odin:165] Parse - reduce sym:string, child_count:1
[DEBUG] --- [helpers.odin:165] Parse - reduce sym:import_declaration, child_count:3
[DEBUG] --- [helpers.odin:165] Parse - reduce sym:declaration, child_count:1
[DEBUG] --- [helpers.odin:165] Parse - shift state:5913
[DEBUG] --- [helpers.odin:165] Parse - process version:0, version_count:1, state:5913, row:4, col:0
[DEBUG] --- [helpers.odin:165] Parse - lex_external state:2, row:4, column:0
[DEBUG] --- [helpers.odin:165] Lex - skip character:10
[DEBUG] --- [helpers.odin:165] Parse - lex_internal state:85, row:4, column:0
[DEBUG] --- [helpers.odin:165] Lex - skip character:10
[DEBUG] --- [helpers.odin:165] Lex - consume character:'/'
[DEBUG] --- [helpers.odin:165] Lex - consume character:'/'
[DEBUG] --- [helpers.odin:165] Lex - consume character:' '
[DEBUG] --- [helpers.odin:165] Lex - consume character:'G'
[DEBUG] --- [helpers.odin:165] Lex - consume character:'e'
[DEBUG] --- [helpers.odin:165] Lex - consume character:'n'
[DEBUG] --- [helpers.odin:165] Lex - consume character:'e'
[DEBUG] --- [helpers.odin:165] Lex - consume character:'r'
[DEBUG] --- [helpers.odin:165] Lex - consume character:'a'
[DEBUG] --- [helpers.odin:165] Lex - consume character:'t'
[DEBUG] --- [helpers.odin:165] Lex - consume character:'e'
[DEBUG] --- [helpers.odin:165] Lex - consume character:'d'
[DEBUG] --- [helpers.odin:165] Lex - consume character:' '
[DEBUG] --- [helpers.odin:165] Lex - consume character:'t'
[DEBUG] --- [helpers.odin:165] Lex - consume character:'h'
[DEBUG] --- [helpers.odin:165] Lex - consume character:'r'
[DEBUG] --- [helpers.odin:165] Lex - consume character:'o'
[DEBUG] --- [helpers.odin:165] Lex - consume character:'u'
[DEBUG] --- [helpers.odin:165] Lex - consume character:'g'
[DEBUG] --- [helpers.odin:165] Lex - consume character:'h'
[DEBUG] --- [helpers.odin:165] Lex - consume character:' '
[DEBUG] --- [helpers.odin:165] Lex - consume character:'`'
[DEBUG] --- [helpers.odin:165] Lex - consume character:'o'
[DEBUG] --- [helpers.odin:165] Lex - consume character:'d'
[DEBUG] --- [helpers.odin:165] Lex - consume character:'i'
[DEBUG] --- [helpers.odin:165] Lex - consume character:'n'
[DEBUG] --- [helpers.odin:165] Lex - consume character:' '
[DEBUG] --- [helpers.odin:165] Lex - consume character:'r'
[DEBUG] --- [helpers.odin:165] Lex - consume character:'u'
[DEBUG] --- [helpers.odin:165] Lex - consume character:'n'
[DEBUG] --- [helpers.odin:165] Lex - consume character:' '
[DEBUG] --- [helpers.odin:165] Lex - consume character:'b'
[DEBUG] --- [helpers.odin:165] Lex - consume character:'u'
[DEBUG] --- [helpers.odin:165] Lex - consume character:'i'
[DEBUG] --- [helpers.odin:165] Lex - consume character:'l'
[DEBUG] --- [helpers.odin:165] Lex - consume character:'d'
[DEBUG] --- [helpers.odin:165] Lex - consume character:' '
[DEBUG] --- [helpers.odin:165] Lex - consume character:'-'
[DEBUG] --- [helpers.odin:165] Lex - consume character:'-'
[DEBUG] --- [helpers.odin:165] Lex - consume character:' '
[DEBUG] --- [helpers.odin:165] Lex - consume character:'i'
[DEBUG] --- [helpers.odin:165] Lex - consume character:'n'
[DEBUG] --- [helpers.odin:165] Lex - consume character:'s'
[DEBUG] --- [helpers.odin:165] Lex - consume character:'t'
[DEBUG] --- [helpers.odin:165] Lex - consume character:'a'
[DEBUG] --- [helpers.odin:165] Lex - consume character:'l'
[DEBUG] --- [helpers.odin:165] Lex - consume character:'l'
[DEBUG] --- [helpers.odin:165] Lex - consume character:'-'
[DEBUG] --- [helpers.odin:165] Lex - consume character:'p'
[DEBUG] --- [helpers.odin:165] Lex - consume character:'a'
[DEBUG] --- [helpers.odin:165] Lex - consume character:'r'
[DEBUG] --- [helpers.odin:165] Lex - consume character:'s'
[DEBUG] --- [helpers.odin:165] Lex - consume character:'e'
[DEBUG] --- [helpers.odin:165] Lex - consume character:'r'
[DEBUG] --- [helpers.odin:165] Lex - consume character:' '
[DEBUG] --- [helpers.odin:165] Lex - consume character:'h'
[DEBUG] --- [helpers.odin:165] Lex - consume character:'t'
[DEBUG] --- [helpers.odin:165] Lex - consume character:'t'
[DEBUG] --- [helpers.odin:165] Lex - consume character:'p'
[DEBUG] --- [helpers.odin:165] Lex - consume character:'s'
[DEBUG] --- [helpers.odin:165] Lex - consume character:':'
[DEBUG] --- [helpers.odin:165] Lex - consume character:'/'
[DEBUG] --- [helpers.odin:165] Lex - consume character:'/'
[DEBUG] --- [helpers.odin:165] Lex - consume character:'g'
[DEBUG] --- [helpers.odin:165] Lex - consume character:'i'
[DEBUG] --- [helpers.odin:165] Lex - consume character:'t'
[DEBUG] --- [helpers.odin:165] Lex - consume character:'h'
[DEBUG] --- [helpers.odin:165] Lex - consume character:'u'
[DEBUG] --- [helpers.odin:165] Lex - consume character:'b'
[DEBUG] --- [helpers.odin:165] Lex - consume character:'.'
[DEBUG] --- [helpers.odin:165] Lex - consume character:'c'
[DEBUG] --- [helpers.odin:165] Lex - consume character:'o'
[DEBUG] --- [helpers.odin:165] Lex - consume character:'m'
[DEBUG] --- [helpers.odin:165] Lex - consume character:'/'
[DEBUG] --- [helpers.odin:165] Lex - consume character:'a'
[DEBUG] --- [helpers.odin:165] Lex - consume character:'m'
[DEBUG] --- [helpers.odin:165] Lex - consume character:'a'
[DEBUG] --- [helpers.odin:165] Lex - consume character:'a'
[DEBUG] --- [helpers.odin:165] Lex - consume character:'n'
[DEBUG] --- [helpers.odin:165] Lex - consume character:'q'
[DEBUG] --- [helpers.odin:165] Lex - consume character:'/'
[DEBUG] --- [helpers.odin:165] Lex - consume character:'t'
[DEBUG] --- [helpers.odin:165] Lex - consume character:'r'
[DEBUG] --- [helpers.odin:165] Lex - consume character:'e'
[DEBUG] --- [helpers.odin:165] Lex - consume character:'e'
[DEBUG] --- [helpers.odin:165] Lex - consume character:'-'
[DEBUG] --- [helpers.odin:165] Lex - consume character:'s'
[DEBUG] --- [helpers.odin:165] Lex - consume character:'i'
[DEBUG] --- [helpers.odin:165] Lex - consume character:'t'
[DEBUG] --- [helpers.odin:165] Lex - consume character:'t'
[DEBUG] --- [helpers.odin:165] Lex - consume character:'e'
[DEBUG] --- [helpers.odin:165] Lex - consume character:'r'
[DEBUG] --- [helpers.odin:165] Lex - consume character:'-'
[DEBUG] --- [helpers.odin:165] Lex - consume character:'o'
[DEBUG] --- [helpers.odin:165] Lex - consume character:'d'
[DEBUG] --- [helpers.odin:165] Lex - consume character:'i'
[DEBUG] --- [helpers.odin:165] Lex - consume character:'n'
[DEBUG] --- [helpers.odin:165] Lex - consume character:'`'
[DEBUG] --- [helpers.odin:165] Parse - lexed_lookahead sym:comment, size:99
[DEBUG] --- [helpers.odin:165] Parse - shift_extra
[DEBUG] --- [helpers.odin:165] Parse - process version:0, version_count:1, state:5913, row:5, col:98
[DEBUG] --- [helpers.odin:165] Parse - lex_external state:2, row:5, column:98
[DEBUG] --- [helpers.odin:165] Lex - skip character:10
[DEBUG] --- [helpers.odin:165] Parse - lex_internal state:85, row:5, column:98
[DEBUG] --- [helpers.odin:165] Lex - skip character:10
[DEBUG] --- [helpers.odin:165] Lex - consume character:'i'
[DEBUG] --- [helpers.odin:165] Lex - consume character:'m'
[DEBUG] --- [helpers.odin:165] Lex - consume character:'p'
[DEBUG] --- [helpers.odin:165] Lex - consume character:'o'
[DEBUG] --- [helpers.odin:165] Lex - consume character:'r'
[DEBUG] --- [helpers.odin:165] Lex - consume character:'t'
[DEBUG] --- [helpers.odin:165] Lex - consume character:'i'
[DEBUG] --- [helpers.odin:165] Lex - consume character:'m'
[DEBUG] --- [helpers.odin:165] Lex - consume character:'p'
[DEBUG] --- [helpers.odin:165] Lex - consume character:'o'
[DEBUG] --- [helpers.odin:165] Lex - consume character:'r'
[DEBUG] --- [helpers.odin:165] Lex - consume character:'t'
[DEBUG] --- [helpers.odin:165] Parse - lexed_lookahead sym:import, size:7
[DEBUG] --- [helpers.odin:165] Parse - reduce sym:source_file_repeat1, child_count:2
[DEBUG] --- [helpers.odin:165] Parse - reduce sym:source_file_repeat1, child_count:2
 ```
 </details>
 <details>
 <summary>gdb backtrace</summary>

```
(gdb) bt
#0  0x00007ffff7e1474c in ?? () from /usr/lib/libc.so.6
#1  0x000000000040a4ea in runtime.mem_copy_non_overlapping (dst=0x69d770 "", src=0x69d6f0 "\200\304i", len=9223372036854775807) at /home/leto/Git/Odin/base/runtime/internal.odin:113
#2  0x000000000044200c in runtime.heap_allocator_proc.aligned_alloc-0 (size=104, alignment=16, old_ptr=0x69d6f0 "\200\304i", old_size=9223372036854775807, zero_memory=true)
    at /home/leto/Git/Odin/base/runtime/heap_allocator.odin:51
#3  0x0000000000442243 in runtime.heap_allocator_proc.aligned_resize-2 (p=0x69d6f0 "\200\304i", old_size=9223372036854775807, new_size=104, new_alignment=16, zero_memory=true)
    at /home/leto/Git/Odin/base/runtime/heap_allocator.odin:69
#4  0x00000000004027ee in runtime.heap_allocator_proc (allocator_data=0x0, mode=Resize, size=104, alignment=16, old_memory=0x69d6f0 "\200\304i", old_size=9223372036854775807)
    at /home/leto/Git/Odin/base/runtime/heap_allocator.odin:90
#5  0x00000000004096cc in mem.tracking_allocator_proc (allocator_data=0x7fffffffdae0 "0&@", mode=Resize, size=104, alignment=16, old_memory=0x69d6f0 "\200\304i", old_size=9223372036854775807, loc=...)
    at /home/leto/Git/Odin/core/mem/tracking_allocator.odin:122
#6  0x00000000004144e9 in runtime._mem_resize (ptr=0x69d6f0 "\200\304i", old_size=9223372036854775807, new_size=104, alignment=16, allocator=..., should_zero=true, loc=...)
    at /home/leto/Git/Odin/base/runtime/internal.odin:198
#7  0x0000000000417d0c in runtime.mem_resize (ptr=0x69d6f0 "\200\304i", old_size=9223372036854775807, new_size=104, alignment=16, allocator=..., loc=...) at /home/leto/Git/Odin/base/runtime/internal.odin:218
#8  0x0000000000442b0d in ts.set_odin_allocator.odin_realloc-2 (ptr=0x69d6f0 "\200\304i", size=104) at /home/leto/Programming/Odin/odin_treesitter/tree-sitter/helpers.odin:48
#9  0x000000000046619a in ts_subtree_new_node ()
#10 0x0000000000451766 in ts_parser_parse ()
#11 0x000000000045389f in ts_parser_parse_string_encoding ()
#12 0x00000000004073d6 in ts.parser_parse_string (self=0x69b2e0 " ", string=..., old_tree=0x0) at /home/leto/Programming/Odin/odin_treesitter/tree-sitter/wrappers.odin:44
#13 0x00000000004033f7 in main.main () at main.odin:54
#14 0x000000000040776c in main (argc=1, argv=0x7fffffffde98) at /home/leto/Git/Odin/base/runtime/entry_unix.odin:57
(gdb)
```
</details>

**Comment by laytan** [comment]
Hello! I looked into this and https://github.com/odin-lang/Odin/commit/bed18a17e6fbad407ac0304e5ca0b3058e1d9276 basically broke the use of the default allocator with the package directly. I made this commit: https://github.com/laytan/odin-tree-sitter/commit/1f6bafd4d95eaf996a693904c24cff988bea5025 to indicate you basically always need the compat allocator (or just not set an Odin allocator at all).

Thanks for letting me know!
